packages:
    asm89/stack-cors: v2.3.0
    behat/mink: v1.12.0
    behat/mink-browserkit-driver: v2.2.0
    brick/math: 0.14.0
    chi-teck/drupal-code-generator: 4.2.0
    colinodell/psr-testlogger: v1.3.0
    composer/ca-bundle: 1.5.8
    composer/class-map-generator: 1.6.2
    composer/composer: 2.8.12
    composer/installers: v2.3.0
    composer/metadata-minifier: 1.0.0
    composer/pcre: 3.3.2
    composer/semver: 3.4.4
    composer/spdx-licenses: 1.5.9
    composer/xdebug-handler: 3.0.5
    consolidation/annotated-command: 4.10.2
    consolidation/config: 3.1.1
    consolidation/filter-via-dot-access-data: 2.0.2
    consolidation/log: 3.1.0
    consolidation/output-formatters: 4.6.1
    consolidation/robo: 5.1.0
    consolidation/site-alias: 4.1.1
    consolidation/site-process: 5.4.2
    dealerdirect/phpcodesniffer-composer-installer: v1.1.2
    dflydev/dot-access-data: v3.0.3
    doctrine/annotations: 2.0.2
    doctrine/deprecations: 1.1.5
    doctrine/instantiator: 2.0.0
    doctrine/lexer: 2.1.1
    drupal/coder: 8.3.30
    drupal/core: 11.2.5
    drupal/core-composer-scaffold: 11.2.5
    drupal/core-dev: 11.2.5
    drupal/core-project-message: 11.2.5
    drupal/core-recipe-unpack: 11.2.5
    drupal/core-recommended: 11.2.5
    drupal/sdc_component_library: 1.0.0-beta6
    drupal/storybook: 1.0.2
    drush/drush: 13.6.2
    e0ipso/twig-storybook: v1.6.0
    egulias/email-validator: 4.0.4
    google/protobuf: v4.32.1
    grasmash/expander: 3.0.1
    grasmash/yaml-cli: 3.2.1
    guzzlehttp/guzzle: 7.9.3
    guzzlehttp/promises: 2.2.0
    guzzlehttp/psr7: 2.7.1
    joachim-n/composer-manifest: 1.1.7
    justinrainbow/json-schema: 6.5.2
    laravel/prompts: v0.3.7
    league/container: 4.2.5
    lullabot/mink-selenium2-driver: v1.7.4
    lullabot/php-webdriver: v2.0.7
    marc-mabe/php-enum: v4.7.2
    masterminds/html5: 2.9.0
    mck89/peast: v1.17.2
    mglaman/phpstan-drupal: 2.0.9
    micheh/phpcs-gitlab: 2.1.0
    mikey179/vfsstream: v1.6.12
    myclabs/deep-copy: 1.13.4
    nikic/php-parser: v5.6.1
    nyholm/psr7-server: 1.1.0
    open-telemetry/api: 1.7.0
    open-telemetry/context: 1.4.0
    open-telemetry/exporter-otlp: 1.3.2
    open-telemetry/gen-otlp-protobuf: 1.8.0
    open-telemetry/sdk: 1.9.0
    open-telemetry/sem-conv: 1.37.0
    pear/archive_tar: 1.5.0
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.16
    pear/pear_exception: v1.0.2
    phar-io/manifest: 2.0.4
    phar-io/version: 3.2.1
    phootwork/collection: v3.2.3
    phootwork/lang: v3.2.3
    php-http/discovery: 1.20.0
    php-http/guzzle7-adapter: 1.1.0
    php-http/httplug: 2.4.1
    php-http/promise: 1.3.1
    php-tuf/composer-stager: v2.0.1
    phpdocumentor/reflection-common: 2.2.0
    phpdocumentor/reflection-docblock: 5.6.3
    phpdocumentor/type-resolver: 1.10.0
    phpowermove/docblock: v4.0
    phpspec/prophecy: v1.22.0
    phpspec/prophecy-phpunit: v2.4.0
    phpstan/extension-installer: 1.4.3
    phpstan/phpdoc-parser: 2.3.0
    phpstan/phpstan: 2.1.30
    phpstan/phpstan-deprecation-rules: 2.0.3
    phpstan/phpstan-phpunit: 2.0.7
    phpunit/php-code-coverage: 11.0.11
    phpunit/php-file-iterator: 5.1.0
    phpunit/php-invoker: 5.0.1
    phpunit/php-text-template: 4.0.1
    phpunit/php-timer: 7.0.1
    phpunit/phpunit: 11.5.42
    psr/cache: 3.0.0
    psr/container: 2.0.2
    psr/event-dispatcher: 1.0.0
    psr/http-client: 1.0.3
    psr/http-factory: 1.1.0
    psr/http-message: '2.0'
    psr/log: 3.0.2
    psy/psysh: v0.12.12
    ralouphie/getallheaders: 3.0.3
    ramsey/collection: 2.1.1
    ramsey/uuid: 4.9.1
    react/promise: v3.3.0
    revolt/event-loop: v1.0.7
    sebastian/cli-parser: 3.0.2
    sebastian/code-unit: 3.0.3
    sebastian/code-unit-reverse-lookup: 4.0.1
    sebastian/comparator: 6.3.2
    sebastian/complexity: 4.0.1
    sebastian/diff: 6.0.2
    sebastian/environment: 7.2.1
    sebastian/exporter: 6.3.2
    sebastian/global-state: 7.0.2
    sebastian/lines-of-code: 3.0.1
    sebastian/object-enumerator: 6.0.1
    sebastian/object-reflector: 4.0.1
    sebastian/recursion-context: 6.0.3
    sebastian/type: 5.1.3
    sebastian/version: 5.0.2
    seld/jsonlint: 1.11.0
    seld/phar-utils: 1.2.1
    seld/signal-handler: 2.0.2
    sirbrillig/phpcs-variable-analysis: v2.13.0
    slevomat/coding-standard: 8.22.1
    squizlabs/php_codesniffer: 3.13.4
    staabm/side-effects-detector: 1.0.5
    symfony/browser-kit: v7.3.2
    symfony/console: v7.3.4
    symfony/css-selector: v7.3.0
    symfony/dependency-injection: v7.3.4
    symfony/deprecation-contracts: v3.6.0
    symfony/dom-crawler: v7.3.3
    symfony/error-handler: v7.3.4
    symfony/event-dispatcher: v7.3.3
    symfony/event-dispatcher-contracts: v3.6.0
    symfony/filesystem: v7.3.2
    symfony/finder: v7.3.2
    symfony/http-foundation: v7.3.4
    symfony/http-kernel: v7.3.4
    symfony/lock: v7.3.4
    symfony/mailer: v7.3.4
    symfony/mime: v7.3.4
    symfony/polyfill-ctype: v1.32.0
    symfony/polyfill-iconv: v1.32.0
    symfony/polyfill-intl-grapheme: v1.32.0
    symfony/polyfill-intl-idn: v1.32.0
    symfony/polyfill-intl-normalizer: v1.32.0
    symfony/polyfill-mbstring: v1.32.0
    symfony/polyfill-php73: v1.33.0
    symfony/polyfill-php80: v1.33.0
    symfony/polyfill-php81: v1.33.0
    symfony/polyfill-php82: v1.33.0
    symfony/polyfill-php83: v1.33.0
    symfony/polyfill-php84: v1.32.0
    symfony/process: v7.3.4
    symfony/psr-http-message-bridge: v7.3.0
    symfony/routing: v7.3.4
    symfony/serializer: v7.3.4
    symfony/service-contracts: v3.6.0
    symfony/string: v7.3.4
    symfony/translation-contracts: v3.6.0
    symfony/validator: v7.3.4
    symfony/var-dumper: v7.3.4
    symfony/var-exporter: v7.3.4
    symfony/yaml: v7.3.3
    tbachert/spi: v1.0.5
    theseer/tokenizer: 1.2.3
    twig/twig: v3.21.1
    webflo/drupal-finder: 1.3.1
    webmozart/assert: 1.11.0
